language: node_js
node_js:
- "stable"

branches:
  only:
    - master

script:
- jest --updateSnapshot
- npm test
- CI=true npm run build --base-href https://jordystabel.github.io/AutoScout23_Frontend/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master