language: node_js
node_js:
- "stable"

branches:
  only:
    - master

script:
#- npm test (Used for Jest testing, is replaced by Cypress)
-  $(npm bin)/cypress run
- CI=true npm run build --base-href https://jordystabel.github.io/AutoScout23_Frontend/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master